// All user-facing copy for the booking and checkout pages. Add a locale here and switch LOCALE to translate.
const en = {
    booking: {
        back: 'Go back',
        titleLoading: 'Placing your booking…',
        titleSuccess: 'Booking confirmed!',
        titleError: 'Booking failed',
        steps: ['Checking availability…', 'Reserving your tickets…', 'Confirming booking…'],
        redirecting: 'Taking you to your booking info…',
        soldOut: (ticket: string) => `“${ticket}” is sold out or no longer available in that quantity.`,
        genericError: 'Something went wrong while placing your booking. Please try again.',
        continue: 'Continue',
        backToEvent: 'Back to event',
        tryAgain: 'Try again',
        backToTickets: 'Back to tickets',
        subtotal: 'Subtotal',
        free: 'Free',
    },
    checkout: {
        title: 'Booking Info',
        back: 'Go back',
        ticketCount: (n: number) => `${n} ${n === 1 ? 'ticket' : 'tickets'}`,
        toggleSummary: 'Toggle order summary',
        free: 'Free',
        bookingDetails: 'Booking details',
        masterId: 'Master ID',
        placedDate: 'Placed date',
        copy: 'Copy master ID',
        copied: 'Copied',
        contact: 'Contact information',
        firstName: 'First name*',
        lastName: 'Last name*',
        phone: 'Phone number*',
        email: 'Email*',
        country: 'Country code',
        required: 'This field is required',
        invalidPhone: 'Enter a valid phone number',
        invalidEmail: 'Enter a valid email address',
        addCoupon: 'Add coupon',
        addCode: 'Add code',
        reserve: 'Reserve',
        paymentTitle: 'Payment Methods',
        choosePayment: 'Choose a payment',
        unavailable: 'Unavailable',
        payNow: 'Pay Now',
        contactName: 'Name',
        contactPhone: 'Phone number',
        contactEmail: 'Email',
        reservedTitle: 'Reserved!',
        reservedMessage: (name: string, email: string) => `Thanks ${name}, your tickets are reserved. We'll send the details to ${email}.`,
        backToEvent: 'Back to event',
        couponPlaceholder: 'Coupon code',
        apply: 'Apply',
        invalidCoupon: 'This coupon code is not valid',
        removeCoupon: 'Remove coupon',
    },
};

const km: typeof en = {
    booking: {
        back: 'ថយក្រោយ',
        titleLoading: 'កំពុងដាក់ការកក់របស់អ្នក…',
        titleSuccess: 'ការកក់ត្រូវបានបញ្ជាក់!',
        titleError: 'ការកក់បរាជ័យ',
        steps: ['កំពុងពិនិត្យភាពអាចរកបាន…', 'កំពុងរក្សាទុកសំបុត្ររបស់អ្នក…', 'កំពុងបញ្ជាក់ការកក់…'],
        redirecting: 'កំពុងបន្តទៅព័ត៌មានការកក់…',
        soldOut: (ticket) => `សំបុត្រ “${ticket}” លក់អស់ ឬមិនមានចំនួនដែលអ្នកស្នើសុំទេ។`,
        genericError: 'មានបញ្ហាក្នុងការដាក់ការកក់។ សូមព្យាយាមម្តងទៀត។',
        continue: 'បន្ត',
        backToEvent: 'ត្រឡប់ទៅព្រឹត្តិការណ៍',
        tryAgain: 'ព្យាយាមម្តងទៀត',
        backToTickets: 'ត្រឡប់ទៅសំបុត្រ',
        subtotal: 'សរុបរង',
        free: 'ឥតគិតថ្លៃ',
    },
    checkout: {
        title: 'ព័ត៌មានការកក់',
        back: 'ថយក្រោយ',
        ticketCount: (n) => `${n} សំបុត្រ`,
        toggleSummary: 'បើក/បិទសេចក្តីសង្ខេបការកក់',
        free: 'ឥតគិតថ្លៃ',
        bookingDetails: 'ព័ត៌មានលម្អិតនៃការកក់',
        masterId: 'លេខសម្គាល់ការកក់',
        placedDate: 'កាលបរិច្ឆេទកក់',
        copy: 'ចម្លងលេខសម្គាល់',
        copied: 'បានចម្លង',
        contact: 'ព័ត៌មានទំនាក់ទំនង',
        firstName: 'នាមខ្លួន*',
        lastName: 'នាមត្រកូល*',
        phone: 'លេខទូរស័ព្ទ*',
        email: 'អ៊ីមែល*',
        country: 'កូដប្រទេស',
        required: 'តម្រូវឱ្យបំពេញ',
        invalidPhone: 'សូមបញ្ចូលលេខទូរស័ព្ទឱ្យត្រឹមត្រូវ',
        invalidEmail: 'សូមបញ្ចូលអាសយដ្ឋានអ៊ីមែលឱ្យត្រឹមត្រូវ',
        addCoupon: 'បន្ថែមគូប៉ុង',
        addCode: 'បន្ថែមកូដ',
        reserve: 'កក់',
        paymentTitle: 'វិធីបង់ប្រាក់',
        choosePayment: 'ជ្រើសរើសវិធីបង់ប្រាក់',
        unavailable: 'មិនអាចប្រើបាន',
        payNow: 'បង់ឥឡូវនេះ',
        contactName: 'ឈ្មោះ',
        contactPhone: 'លេខទូរស័ព្ទ',
        contactEmail: 'អ៊ីមែល',
        reservedTitle: 'បានកក់ហើយ!',
        reservedMessage: (name, email) => `អរគុណ ${name} សំបុត្ររបស់អ្នកត្រូវបានកក់ហើយ។ យើងនឹងផ្ញើព័ត៌មានលម្អិតទៅ ${email}។`,
        backToEvent: 'ត្រឡប់ទៅព្រឹត្តិការណ៍',
        couponPlaceholder: 'កូដគូប៉ុង',
        apply: 'អនុវត្ត',
        invalidCoupon: 'កូដគូប៉ុងមិនត្រឹមត្រូវ',
        removeCoupon: 'លុបគូប៉ុង',
    },
};

const locales = { en, km };
export type Locale = keyof typeof locales;

const LOCALE: Locale = 'en';

export const labels = locales[LOCALE];
